services:
  mysql-una:
    image: mysql:8.0
    container_name: mysql-una
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: una_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - una_mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  una_mysql_data:
